DROP TABLE acl_sid;
CREATE TABLE acl_sid ( id bigint unsigned NOT NULL AUTO_INCREMENT, principal tinyint(1) NOT NULL, sid varchar(100) NOT NULL, PRIMARY KEY (id), CONSTRAINT acl_sid_idx_1 UNIQUE (sid, principal) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE acl_class;
CREATE TABLE acl_class ( id bigint unsigned NOT NULL AUTO_INCREMENT, class varchar(100) NOT NULL, PRIMARY KEY (id), CONSTRAINT class UNIQUE (class) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE acl_object_identity;
CREATE TABLE acl_object_identity ( id bigint unsigned NOT NULL AUTO_INCREMENT, object_id_class bigint unsigned NOT NULL, object_id_identity bigint unsigned NOT NULL, parent_object bigint unsigned, owner_sid bigint unsigned, entries_inheriting tinyint(1) NOT NULL, PRIMARY KEY (id), FOREIGN KEY (object_id_class) REFERENCES acl_class (id) , FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id) , FOREIGN KEY (owner_sid) REFERENCES acl_sid (id), CONSTRAINT acl_object_identity_idx_1 UNIQUE (object_id_class, object_id_identity), INDEX parent_object (parent_object), INDEX owner_sid (owner_sid) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE acl_entry;
CREATE TABLE acl_entry ( id bigint unsigned NOT NULL AUTO_INCREMENT, acl_object_identity bigint unsigned NOT NULL, ace_order int(10) unsigned NOT NULL, sid bigint unsigned NOT NULL, mask int NOT NULL, granting tinyint(1) NOT NULL, audit_success tinyint(1) NOT NULL, audit_failure tinyint(1) NOT NULL, PRIMARY KEY (id), FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity (id) , FOREIGN KEY (sid) REFERENCES acl_sid (id), CONSTRAINT acl_entry_idx_1 UNIQUE (acl_object_identity, ace_order), INDEX sid (sid) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE authorities;
CREATE TABLE authorities ( username varchar(50) NOT NULL, authority varchar(50) NOT NULL, FOREIGN KEY (username) REFERENCES users (username), CONSTRAINT authorities_idx_1 UNIQUE (username, authority) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into authorities (username, authority) values ('default_user', 'ROLE_USER');
DROP TABLE group_authorities;
CREATE TABLE group_authorities ( group_id bigint unsigned NOT NULL, authority varchar(50) NOT NULL, FOREIGN KEY (group_id) REFERENCES groups (id), INDEX group_id (group_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE group_members;
CREATE TABLE group_members ( id bigint unsigned NOT NULL AUTO_INCREMENT, username varchar(50) NOT NULL, group_id bigint unsigned NOT NULL, PRIMARY KEY (id), FOREIGN KEY (group_id) REFERENCES groups (id), INDEX group_id (group_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE groups;
CREATE TABLE groups ( id bigint unsigned NOT NULL AUTO_INCREMENT, group_name varchar(50) NOT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into groups (id, group_name) values (1, 'default_group');
DROP TABLE oauth_access_token;
CREATE TABLE oauth_access_token ( token_id varchar(256), token blob, authentication_id varchar(256), user_name varchar(256), client_id varchar(256), authentication blob, refresh_token varchar(256), access_token_validity int, refresh_token_validity int ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE oauth_client_details;
CREATE TABLE oauth_client_details ( client_id varchar(256) NOT NULL, resource_ids varchar(1024), client_secret varchar(256), scope varchar(256), authorized_grant_types varchar(256), web_server_redirect_uri varchar(1024), authorities varchar(256), access_token_validity int DEFAULT '0', refresh_token_validity int DEFAULT '0', additional_information varchar(4096), PRIMARY KEY (client_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information) values ('nimble', null, 'mysecret', null, 'authorization_code,refresh_token', 'http://localhost:8080/nimble-provider', 'CLIENT', 600, 0, null);
DROP TABLE oauth_code;
CREATE TABLE oauth_code ( code varchar(255) NOT NULL, authentication blob NOT NULL, PRIMARY KEY (code) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE oauth_refresh_token;
CREATE TABLE oauth_refresh_token ( TOKEN_ID varchar(64) NOT NULL, TOKEN blob NOT NULL, authentication blob NOT NULL, PRIMARY KEY (TOKEN_ID) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE persistent_logins;
CREATE TABLE persistent_logins ( username varchar(64) NOT NULL, series varchar(64) NOT NULL, token varchar(64) NOT NULL, last_used timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (series) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE users;
CREATE TABLE users ( username varchar(50) NOT NULL, password varchar(50) NOT NULL, enabled tinyint(1) NOT NULL, PRIMARY KEY (username) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into users (username, password, enabled) values ('default_user', 'NULL_VALUE', true);
